/*******************************************************************************
 * Copyright (C) 2010 - 2016. TIBCO Software Inc. 
 * All Rights Reserved. Confidential & Proprietary.
 ******************************************************************************/
/*
* generated by Xtext
*/
package com.jaspersoft.studio.editor.jrexpressions.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class JavaJRExpressionOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
