/*
 * Copyright (C) 2003, 2004  Pascal Essiembre, Essiembre Consultant Inc.
 * 
 * This file is part of Essiembre ResourceBundle Editor.
 * 
 * Essiembre ResourceBundle Editor is free software; you can redistribute it 
 * and/or modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 * 
 * Essiembre ResourceBundle Editor is distributed in the hope that it will be 
 * useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with Essiembre ResourceBundle Editor; if not, write to the 
 * Free Software Foundation, Inc., 59 Temple Place, Suite 330, 
 * Boston, MA  02111-1307  USA
 */
package com.essiembre.eclipse.rbe.ui.preferences;

import org.eclipse.core.runtime.preferences.IEclipsePreferences;
import org.eclipse.jface.preference.IPreferenceStore;
import org.eclipse.swt.SWT;
import org.eclipse.swt.events.SelectionAdapter;
import org.eclipse.swt.events.SelectionEvent;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.layout.RowLayout;
import org.eclipse.swt.widgets.Button;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Label;
import org.eclipse.swt.widgets.Text;

import com.essiembre.eclipse.rbe.RBEPlugin;
import com.essiembre.eclipse.rbe.model.workbench.RBEPreferences;

/**
 * Plugin preference page.
 * @author Pascal Essiembre (essiembre@users.sourceforge.net)
 * @version $Author: essiembre $ $Revision: 1.5 $ $Date: 2007/02/02 04:16:48 $
 */
public class RBEFormattingPrefPage extends AbstractRBEPrefPage {
    
    /* Preference fields. */
    private Button showGeneratedBy;

    private Button convertUnicodeToEncoded;
    private Button convertUnicodeUpperCase;

    private Button alignEqualSigns;
    private Button ensureSpacesAroundEquals;
    
    private Button groupKeys;
    private Text groupLevelDeep;
    private Text groupLineBreaks;
    private Button groupAlignEqualSigns;
    
    private Button wrapLines;
    private Text wrapCharLimit;
    private Button wrapAlignEqualSigns;
    private Text wrapIndentSpaces;
    private Button wrapNewLine;
    
    private Button newLineTypeForce;
    private Button[] newLineTypes = new Button[3];

    private Button keepEmptyFields;
    
    /**
     * Constructor.
     */
    public RBEFormattingPrefPage() {
        super();
    }

    /**
     * @see org.eclipse.jface.preference.PreferencePage#createContents(
     *         org.eclipse.swt.widgets.Composite)
     */
    protected Control createContents(Composite parent) {
  	  	IEclipsePreferences prefs = getEclipsePreferenceStore();
        Composite field = null;
        Composite composite = new Composite(parent, SWT.NONE);
        composite.setLayout(new GridLayout(1, false));
        
        // Show generated by comment?
        field = createFieldComposite(composite);
        showGeneratedBy = new Button(field, SWT.CHECK);
        showGeneratedBy.setSelection(prefs.getBoolean(RBEPreferences.SHOW_GENERATOR, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.showGeneratedBy")); //$NON-NLS-1$

        // Convert unicode to encoded?
        field = createFieldComposite(composite);
        convertUnicodeToEncoded = new Button(field, SWT.CHECK);
        convertUnicodeToEncoded.setSelection(
                prefs.getBoolean(RBEPreferences.CONVERT_UNICODE_TO_ENCODED, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        convertUnicodeToEncoded.addSelectionListener(new SelectionAdapter() {
            public void widgetSelected(SelectionEvent event) {
                refreshEnabledStatuses();
            }
        });
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.convertUnicode")); //$NON-NLS-1$

        // Use upper case for encoded hexadecimal values?
        field = createFieldComposite(composite, indentPixels);
        convertUnicodeUpperCase = new Button(field, SWT.CHECK);
        convertUnicodeUpperCase.setSelection(prefs.getBoolean(RBEPreferences.CONVERT_UNICODE_TO_ENCODED_UPPER, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.convertUnicode.upper"));//$NON-NLS-1$
        
        // Align equal signs?
        field = createFieldComposite(composite);
        alignEqualSigns = new Button(field, SWT.CHECK);
        alignEqualSigns.setSelection(prefs.getBoolean(RBEPreferences.ALIGN_EQUAL_SIGNS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        alignEqualSigns.addSelectionListener(new SelectionAdapter() {
            public void widgetSelected(SelectionEvent event) {
                refreshEnabledStatuses();
            }
        });
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.alignEquals")); //$NON-NLS-1$

        field = createFieldComposite(composite);
        ensureSpacesAroundEquals = new Button(field, SWT.CHECK);
        ensureSpacesAroundEquals.setSelection(prefs.getBoolean(RBEPreferences.SPACES_AROUND_EQUAL_SIGNS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.spacesAroundEquals")); //$NON-NLS-1$
        
        // Group keys?
        field = createFieldComposite(composite);
        groupKeys = new Button(field, SWT.CHECK);
        groupKeys.setSelection(prefs.getBoolean(RBEPreferences.GROUP_KEYS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        groupKeys.addSelectionListener(new SelectionAdapter() {
            public void widgetSelected(SelectionEvent event) {
                refreshEnabledStatuses();
            }
        });
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.groupKeys")); //$NON-NLS-1$

        // Group keys by how many level deep?
        field = createFieldComposite(composite, indentPixels);
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.levelDeep")); //$NON-NLS-1$
        groupLevelDeep = new Text(field, SWT.BORDER);
        groupLevelDeep.setText(prefs.get(RBEPreferences.GROUP_LEVEL_DEEP, IPreferenceStore.STRING_DEFAULT_DEFAULT));
        groupLevelDeep.setTextLimit(2);
        setWidthInChars(groupLevelDeep, 2);
        groupLevelDeep.addKeyListener(new IntTextValidatorKeyListener(
                RBEPlugin.getString(
                        "prefs.levelDeep.error"))); //$NON-NLS-1$
        
        // How many lines between groups?
        field = createFieldComposite(composite, indentPixels);
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.linesBetween")); //$NON-NLS-1$
        groupLineBreaks = new Text(field, SWT.BORDER);
        groupLineBreaks.setText(prefs.get(RBEPreferences.GROUP_LINE_BREAKS, IPreferenceStore.STRING_DEFAULT_DEFAULT));
        groupLineBreaks.setTextLimit(2);
        setWidthInChars(groupLineBreaks, 2);
        groupLineBreaks.addKeyListener(new IntTextValidatorKeyListener(
                RBEPlugin.getString(
                        "prefs.linesBetween.error"))); //$NON-NLS-1$

        // Align equal signs within groups?
        field = createFieldComposite(composite, indentPixels);
        groupAlignEqualSigns = new Button(field, SWT.CHECK);
        groupAlignEqualSigns.setSelection(prefs.getBoolean(RBEPreferences.GROUP_ALIGN_EQUAL_SIGNS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString(
                        "prefs.groupAlignEquals")); //$NON-NLS-1$

        // Wrap lines?
        field = createFieldComposite(composite);
        wrapLines = new Button(field, SWT.CHECK);
        wrapLines.setSelection(prefs.getBoolean(RBEPreferences.WRAP_LINES, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        wrapLines.addSelectionListener(new SelectionAdapter() {
            public void widgetSelected(SelectionEvent event) {
                refreshEnabledStatuses();
            }
        });
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.wrapLines")); //$NON-NLS-1$
        
        // After how many characters should we wrap?
        field = createFieldComposite(composite, indentPixels);
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.wrapLinesChar")); //$NON-NLS-1$
        wrapCharLimit = new Text(field, SWT.BORDER);
        wrapCharLimit.setText(prefs.get(RBEPreferences.WRAP_CHAR_LIMIT, IPreferenceStore.STRING_DEFAULT_DEFAULT));
        wrapCharLimit.setTextLimit(4);
        setWidthInChars(wrapCharLimit, 4);
        wrapCharLimit.addKeyListener(new IntTextValidatorKeyListener(
                RBEPlugin.getString(
                        "prefs.wrapLinesChar.error"))); //$NON-NLS-1$
        
        // Align wrapped lines with equal signs?
        field = createFieldComposite(composite, indentPixels);
        wrapAlignEqualSigns = new Button(field, SWT.CHECK);
        wrapAlignEqualSigns.setSelection(prefs.getBoolean(RBEPreferences.WRAP_ALIGN_EQUAL_SIGNS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        wrapAlignEqualSigns.addSelectionListener(new SelectionAdapter() {
            public void widgetSelected(SelectionEvent event) {
                refreshEnabledStatuses();
            }
        });
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.wrapAlignEquals")); //$NON-NLS-1$

        // How many spaces/tabs to use for indenting?
        field = createFieldComposite(composite, indentPixels);
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.wrapIndent")); //$NON-NLS-1$
        wrapIndentSpaces = new Text(field, SWT.BORDER);
        wrapIndentSpaces.setText(prefs.get(RBEPreferences.WRAP_INDENT_SPACES, IPreferenceStore.STRING_DEFAULT_DEFAULT));
        wrapIndentSpaces.setTextLimit(2);
        setWidthInChars(wrapIndentSpaces, 2);
        wrapIndentSpaces.addKeyListener(new IntTextValidatorKeyListener(
                RBEPlugin.getString(
                        "prefs.wrapIndent.error"))); //$NON-NLS-1$

        // Should we wrap after new line characters
        field = createFieldComposite(composite);
        wrapNewLine = new Button(field, SWT.CHECK);
        wrapNewLine.setSelection(prefs.getBoolean(RBEPreferences.NEW_LINE_NICE, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString(
                        "prefs.newline.nice")); //$NON-NLS-1$

        // How should new lines appear in properties file
        field = createFieldComposite(composite);
        newLineTypeForce = new Button(field, SWT.CHECK);
        newLineTypeForce.setSelection(prefs.getBoolean(RBEPreferences.FORCE_NEW_LINE_TYPE, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        newLineTypeForce.addSelectionListener(new SelectionAdapter() {
            public void widgetSelected(SelectionEvent event) {
                refreshEnabledStatuses();
            }
        });
        Composite newLineRadioGroup = new Composite(field, SWT.NONE); 
        new Label(newLineRadioGroup, SWT.NONE).setText(
                RBEPlugin.getString(
                        "prefs.newline.force")); //$NON-NLS-1$
        newLineRadioGroup.setLayout(new RowLayout());
        newLineTypes[RBEPreferences.NEW_LINE_UNIX] = 
                new Button(newLineRadioGroup, SWT.RADIO);
        newLineTypes[RBEPreferences.NEW_LINE_UNIX].setText(
                "UNIX (\\n)"); //$NON-NLS-1$
        newLineTypes[RBEPreferences.NEW_LINE_WIN] = 
                new Button(newLineRadioGroup, SWT.RADIO);
        newLineTypes[RBEPreferences.NEW_LINE_WIN].setText(
                "Windows (\\r\\n)"); //$NON-NLS-1$
        newLineTypes[RBEPreferences.NEW_LINE_MAC] =
                new Button(newLineRadioGroup, SWT.RADIO);
        newLineTypes[RBEPreferences.NEW_LINE_MAC].setText(
                "Mac (\\r)"); //$NON-NLS-1$
        newLineTypes[prefs.getInt(RBEPreferences.NEW_LINE_TYPE, IPreferenceStore.INT_DEFAULT_DEFAULT)].setSelection(true);
        
        // Keep empty fields?
        field = createFieldComposite(composite);
        keepEmptyFields = new Button(field, SWT.CHECK);
        keepEmptyFields.setSelection(prefs.getBoolean(RBEPreferences.KEEP_EMPTY_FIELDS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        new Label(field, SWT.NONE).setText(
                RBEPlugin.getString("prefs.keepEmptyFields"));//$NON-NLS-1$
        
        refreshEnabledStatuses();
        
        return composite;
    }


    /**
     * @see org.eclipse.jface.preference.IPreferencePage#performOk()
     */
    public boolean performOk() {
  	  	IEclipsePreferences prefs = getEclipsePreferenceStore();
        prefs.putBoolean(RBEPreferences.SHOW_GENERATOR, showGeneratedBy.getSelection());
        prefs.putBoolean(RBEPreferences.CONVERT_UNICODE_TO_ENCODED,
                convertUnicodeToEncoded.getSelection());
        prefs.putBoolean(RBEPreferences.CONVERT_UNICODE_TO_ENCODED_UPPER,
                convertUnicodeUpperCase.getSelection());
        prefs.putBoolean(RBEPreferences.ALIGN_EQUAL_SIGNS,
                alignEqualSigns.getSelection());
        prefs.putBoolean(RBEPreferences.SPACES_AROUND_EQUAL_SIGNS,
                ensureSpacesAroundEquals.getSelection());
        prefs.putBoolean(RBEPreferences.GROUP_KEYS,
                groupKeys.getSelection());
        prefs.put(RBEPreferences.GROUP_LEVEL_DEEP,
                groupLevelDeep.getText());
        prefs.put(RBEPreferences.GROUP_LINE_BREAKS,
                groupLineBreaks.getText());
        prefs.putBoolean(RBEPreferences.GROUP_ALIGN_EQUAL_SIGNS,
                groupAlignEqualSigns.getSelection());
        prefs.putBoolean(RBEPreferences.WRAP_LINES,
                wrapLines.getSelection());
        prefs.put(RBEPreferences.WRAP_CHAR_LIMIT,
                wrapCharLimit.getText());
        prefs.putBoolean(RBEPreferences.WRAP_ALIGN_EQUAL_SIGNS,
                wrapAlignEqualSigns.getSelection());
        prefs.put(RBEPreferences.WRAP_INDENT_SPACES,
                wrapIndentSpaces.getText());
        prefs.putBoolean(RBEPreferences.NEW_LINE_NICE,
                wrapNewLine.getSelection());
        prefs.putBoolean(RBEPreferences.FORCE_NEW_LINE_TYPE,
                newLineTypeForce.getSelection());
        for (int i = 0; i < newLineTypes.length; i++) {
            if (newLineTypes[i].getSelection()) {
                prefs.putInt(RBEPreferences.NEW_LINE_TYPE, i);
            }
        }
        prefs.putBoolean(RBEPreferences.KEEP_EMPTY_FIELDS,
                keepEmptyFields.getSelection());
        refreshEnabledStatuses();
        return super.performOk();
    }
    
    
    /**
     * @see org.eclipse.jface.preference.PreferencePage#performDefaults()
     */
    protected void performDefaults() {
    	IEclipsePreferences prefs = getEclipsePreferenceStore();
        showGeneratedBy.setSelection(prefs.getBoolean(RBEPreferences.SHOW_GENERATOR, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        convertUnicodeToEncoded.setSelection(prefs.getBoolean(RBEPreferences.CONVERT_UNICODE_TO_ENCODED, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        convertUnicodeToEncoded.setSelection(prefs.getBoolean(RBEPreferences.CONVERT_UNICODE_TO_ENCODED_UPPER, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        alignEqualSigns.setSelection(prefs.getBoolean(RBEPreferences.ALIGN_EQUAL_SIGNS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        alignEqualSigns.setSelection(prefs.getBoolean(RBEPreferences.SPACES_AROUND_EQUAL_SIGNS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        groupKeys.setSelection(prefs.getBoolean(RBEPreferences.GROUP_KEYS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        groupLevelDeep.setText(prefs.get(RBEPreferences.GROUP_LEVEL_DEEP, IPreferenceStore.STRING_DEFAULT_DEFAULT));
        groupLineBreaks.setText(prefs.get(RBEPreferences.GROUP_LINE_BREAKS, IPreferenceStore.STRING_DEFAULT_DEFAULT));
        groupAlignEqualSigns.setSelection(prefs.getBoolean(RBEPreferences.GROUP_ALIGN_EQUAL_SIGNS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        wrapLines.setSelection(prefs.getBoolean(RBEPreferences.WRAP_LINES, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        wrapCharLimit.setText(prefs.get(RBEPreferences.WRAP_CHAR_LIMIT, IPreferenceStore.STRING_DEFAULT_DEFAULT));
        wrapAlignEqualSigns.setSelection(prefs.getBoolean(RBEPreferences.WRAP_ALIGN_EQUAL_SIGNS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        wrapIndentSpaces.setText(prefs.get(RBEPreferences.WRAP_INDENT_SPACES, IPreferenceStore.STRING_DEFAULT_DEFAULT));
        wrapNewLine.setSelection(prefs.getBoolean(RBEPreferences.NEW_LINE_NICE, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        newLineTypeForce.setSelection(prefs.getBoolean(RBEPreferences.FORCE_NEW_LINE_TYPE, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        newLineTypes[prefs.getInt(RBEPreferences.NEW_LINE_TYPE, IPreferenceStore.INT_DEFAULT_DEFAULT)].setSelection(true);
        keepEmptyFields.setSelection(prefs.getBoolean(RBEPreferences.KEEP_EMPTY_FIELDS, IPreferenceStore.BOOLEAN_DEFAULT_DEFAULT));
        refreshEnabledStatuses();
        super.performDefaults();
    }

    protected void refreshEnabledStatuses() {
        boolean isEncodingUnicode = convertUnicodeToEncoded.getSelection();
        boolean isGroupKeyEnabled = groupKeys.getSelection();
        boolean isAlignEqualsEnabled = alignEqualSigns.getSelection();
        boolean isWrapEnabled = wrapLines.getSelection();
        boolean isWrapAlignEqualsEnabled = wrapAlignEqualSigns.getSelection();
        boolean isNewLineStyleForced = newLineTypeForce.getSelection();

        convertUnicodeUpperCase.setEnabled(isEncodingUnicode);
        groupLevelDeep.setEnabled(isGroupKeyEnabled);
        groupLineBreaks.setEnabled(isGroupKeyEnabled);
        groupAlignEqualSigns.setEnabled(
                isGroupKeyEnabled && isAlignEqualsEnabled);
        wrapCharLimit.setEnabled(isWrapEnabled);
        wrapAlignEqualSigns.setEnabled(isWrapEnabled);
        wrapIndentSpaces.setEnabled(isWrapEnabled && !isWrapAlignEqualsEnabled);
        for (int i = 0; i < newLineTypes.length; i++) {
            newLineTypes[i].setEnabled(isNewLineStyleForced);
        }
    }
    
}
