/*
 * generated by Xtext
 */
package com.jaspersoft.studio.editor.jrexpressions;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JavaJRExpressionRuntimeModule extends com.jaspersoft.studio.editor.jrexpressions.AbstractJavaJRExpressionRuntimeModule {

}
