/*
 * generated by Xtext
 */
package com.jaspersoft.studio.data.ui.outline;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.outline.IOutlineNode;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

import com.jaspersoft.studio.data.sql.Column;
import com.jaspersoft.studio.data.sql.ColumnFull;
import com.jaspersoft.studio.data.sql.ColumnOrAlias;
import com.jaspersoft.studio.data.sql.GroupByColumnFull;
import com.jaspersoft.studio.data.sql.Model;
import com.jaspersoft.studio.data.sql.OrColumn;
import com.jaspersoft.studio.data.sql.OrGroupByColumn;
import com.jaspersoft.studio.data.sql.OrOrderByColumn;
import com.jaspersoft.studio.data.sql.OrTable;
import com.jaspersoft.studio.data.sql.OrderByColumnFull;
import com.jaspersoft.studio.data.sql.Table;
import com.jaspersoft.studio.data.sql.TableFull;
import com.jaspersoft.studio.data.sql.TableOrAlias;

/**
 * Customization of the default outline structure.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#outline
 */
public class SqlOutlineTreeProvider extends org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider {

	@Override
	protected void _createChildren(IOutlineNode parentNode, EObject modelElement) {
		if (modelElement instanceof OrOrderByColumn) {
			OrOrderByColumn ogbc = (OrOrderByColumn) modelElement;
			for (OrderByColumnFull coa : ogbc.getEntries())
				createNode(parentNode, coa.getColOrder());
		} else if (modelElement instanceof OrGroupByColumn) {
			OrGroupByColumn ogbc = (OrGroupByColumn) modelElement;
			for (GroupByColumnFull coa : ogbc.getEntries())
				createNode(parentNode, coa.getGroupByColumn());
		} else if (modelElement instanceof OrTable) {
			OrTable t = (OrTable) modelElement;
			for (TableOrAlias toa : t.getEntries())
				if (toa instanceof TableFull)
					_createChildrenTableFull(parentNode, (TableFull) toa);
				else
					for (EObject eo : toa.eContents())
						if (eo instanceof Table)
							createNode(parentNode, eo);
		} else if (modelElement instanceof TableFull) {
			_createChildrenTableFull(parentNode, (TableFull) modelElement);
		} else if (modelElement instanceof OrColumn) {
			createChildrenColumnOrAlias(parentNode, ((OrColumn) modelElement).getEntries());
		} else if (modelElement instanceof ColumnFull) {
			_createChildrenColumnFull(parentNode, (ColumnFull) modelElement);
		} else
			super._createChildren(parentNode, modelElement);
	}

	protected void createChildrenColumnOrAlias(IOutlineNode parentNode, EList<ColumnOrAlias> list) {
		for (ColumnOrAlias coa : list)
			if (coa instanceof ColumnFull)
				_createChildrenColumnFull(parentNode, (ColumnFull) coa);
			else
				for (EObject eo : coa.eContents())
					if (eo instanceof Column)
						createNode(parentNode, eo);
	}

	protected void _createChildrenTableFull(IOutlineNode parentNode, TableFull cf) {
		if (cf.getTblAlias() != null)
			createNode(parentNode, cf.getTblAlias());
		else if (cf.getTbl() != null)
			createNode(parentNode, cf.getTbl());
	}

	protected void _createChildrenColumnFull(IOutlineNode parentNode, ColumnFull cf) {
		if (cf.getColAlias() != null)
			createNode(parentNode, cf.getColAlias());
		else if (cf.getColName() != null)
			createNode(parentNode, cf.getColName());
	}

	@Override
	protected void _createChildren(Object parent, Object element) {
		super._createChildren(parent, element);
	}

	@Override
	protected void _createChildren(DocumentRootNode parentNode, EObject modelElement) {
		if (modelElement instanceof Model) {
			Model model = (Model) modelElement;
			if (model.getCol() != null)
				createNode(parentNode, model.getCol());
			if (model.getTbl() != null)
				createNode(parentNode, model.getTbl());
			if (model.getWhereEntry() != null)
				createNode(parentNode, model.getWhereEntry());
			if (model.getGroupByEntry() != null)
				createNode(parentNode, model.getGroupByEntry());
			if (model.getHavingEntry() != null)
				createNode(parentNode, model.getHavingEntry());
			if (model.getOrderByEntry() != null)
				createNode(parentNode, model.getOrderByEntry());
		} else
			super._createChildren(parentNode, modelElement);
	}
}
